requestとresponseのパーサを作成します。
libknt/webserv pull request #11
Opened 2023-10-19 05:32 UTC by MasaDevs

2023-10-19 11:52 UTC, libknt reviewed
レビューして良い？

2023-10-22 08:11 UTC, MasaDevs commented on srcs/server/request/http_request.cpp
> +		getInfo();
getInfo()消す

2023-10-22 08:21 UTC, soooku requested changes

2023-10-22 08:21 UTC, soooku commented on srcs/server/request/http_request.cpp
> +	if (parse_sentense(line, "%s %s %s", method_vector) == -1 || method_vector.size() != 3)
![nits](https://img.shields.io/badge/review-nits-inactive.svg)
関数名キャメルでお願いします！

2023-10-22 09:33 UTC, libknt reviewed
ok

2023-10-23 00:42 UTC, MasaDevs reviewed
直しました

2023-10-23 07:08 UTC, soooku commented on srcs/server/request/parse_sentense.hpp
> +int parseSentense(std::string line, std::string const& format, std::vector<std::string>& ans);
![ask](https://img.shields.io/badge/review-ask-informational.svg)
第二引数のansがいまいち何指してるかわからんかった！

2023-10-23 07:14 UTC, soooku commented on srcs/server/request/parse_sentense.hpp
![ask](https://img.shields.io/badge/review-ask-informational.svg)
これみてふとおもったんやけどヘッダファイルの場所どうする？
個人的な意見としては、Cの時よりヘッダファイルと.cppファイルの紐付きが強いからincludesに置かずに.cppと同じ位置に置きたさがある
VSCodeで開いたときに隣にあるの嬉しい

2023-10-23 07:18 UTC, soooku commented on srcs/server/request/parse_http_request.cpp
> +int ParseHttpRequest::parse_http_request(int socketfd, char* buf) {
![nits](https://img.shields.io/badge/review-nits-inactive.svg)
キャメルよろ！

2023-10-23 07:20 UTC, soooku commented on includes/http_request.hpp
> +		int									chunked_status_;
これってどうなった？

2023-10-24 05:08 UTC, libknt reviewed
comment

2023-10-24 05:08 UTC, libknt commented on srcs/server/request/http_request.cpp
> +		// no error handling
//TODOとか付けてもらえると助かるかも

2023-10-24 05:08 UTC, libknt commented on srcs/server/request/parse_http_request.cpp
> +int ParseHttpRequest::parse_http_request(int socketfd, char* buf) {
直ってないみたい！

2023-10-24 05:08 UTC, libknt commented on srcs/server/request/parse_sentense.hpp
統一済み

2023-10-24 05:27 UTC, libknt reviewed
commentしました！よろしくお願いします！

2023-10-24 05:27 UTC, libknt commented on srcs/server/request/http_request.hpp
> +class HttpRequest {
現状、classのnamespaceはserverにしているけどどうする？

2023-10-24 05:27 UTC, libknt commented on srcs/server/request/parse_http_request.cpp
> +		// if error occured, you parseHttpRequest(line) must return -1. So handle it.
//todo

2023-10-24 05:27 UTC, libknt commented on srcs/server/request/http_request.cpp
> +	// Later: http request compromise 0 space between : and value!
//todo

2023-10-24 05:27 UTC, libknt commented on srcs/server/request/http_request.cpp
> +		// Caution ! strtol is C++ 11 function.
todo

2023-10-24 05:27 UTC, libknt commented on srcs/server/request/http_request.cpp
> +	// no error handling
todo

2023-10-24 05:27 UTC, libknt commented on srcs/server/request/parse_http_request.hpp
> +	int parse_http_request(int socketfd, char* buf);
キャメル

2023-10-24 05:27 UTC, libknt commented on srcs/server/request/parse_http_request.hpp
> +#define BUFFER_SIZE 1024
defineする場所変えてio_mult側のchar buffer[1024]も変更して欲しい!

2023-10-24 06:13 UTC, MasaDevs commented on includes/http_request.hpp
> +		HttpRequest();
done

2023-10-24 06:13 UTC, MasaDevs commented on srcs/server/request/http_request_parse.cpp
> +	while ((index = http_line_stream_[socketfd].find("\r\n")) < http_line_stream_[socketfd].size())
done

2023-10-24 06:14 UTC, MasaDevs commented on srcs/server/request/http_request.cpp
> +		std::cout << "Http Method Parse Error" << std::endl;
done

2023-10-24 06:17 UTC, MasaDevs commented on srcs/server/request/parse_sentense.hpp
> +int parseSentense(std::string line, std::string const& format, std::vector<std::string>& ans);
done

2023-10-24 06:18 UTC, MasaDevs commented on srcs/server/request/parse_http_request.cpp
> +int ParseHttpRequest::parse_http_request(int socketfd, char* buf) {
done

2023-10-24 06:18 UTC, MasaDevs commented on webserv.pcapng
done

2023-10-24 06:18 UTC, MasaDevs commented on srcs/server/request/http_request.cpp
> +		// no error handling
done

2023-10-24 06:34 UTC, libknt reviewed
細かいところまでありがとう！
LGTM!
![ミサワ](https://livedoor.blogimg.jp/jigokuno_misawa/imgs/1/f/1f64bd80.gif)

2023-10-24 06:36 UTC, libknt approved these changes
細かいところまでありがとう！
LGTM! 
![ミサワ](https://livedoor.blogimg.jp/jigokuno_misawa/imgs/9/b/9b15a5f9.gif)

2023-10-24 06:44 UTC, soooku approved these changes
対応ありがとう！

2023-10-24 06:44 UTC, merged