バッファサイズが小さいときにHTTPのパースエラーが出るバグを修正しました。
libknt/webserv pull request #35
Opened 2023-11-01 04:45 UTC by MasaDevs

原因は二つ考えられました。
1. テストケースのボディーの最後に\r\nが入ってしまっていた。
2. Bodyのサイズ指定がContent-Lengthの際に、パース後のhttp_line_stream_[socketfd]バッファーをクリアしていなかった。
この二点を修正しました。
テストケースではバッファーサイズが2を想定してtest/unit_test/request/srcs/main.cppに指定しています。

2023-11-02 04:51 UTC, soooku requested changes

2023-11-02 04:51 UTC, soooku commented on srcs/server/request/parse_http_request.cpp
![must](https://img.shields.io/badge/review-must-critical.svg)
chunkedの時に文字列より小さい数値があってもエラーにならない

2023-11-02 05:39 UTC, soooku submitted a review, later dismissed
感謝です！

2023-11-02 08:20 UTC, libknt reviewed
大丈夫そう！
BufferSizeが１だとできないって認識であってます？

2023-11-02 08:20 UTC, libknt commented on srcs/server/request/parse_http_request.cpp
> +		http_line_stream_[socketfd] = "";
http_line-stram[sd].clear();
でお願いします！

2023-11-02 08:20 UTC, libknt commented on test/unit_test/request/srcs/main.cpp
> +#ifndef BUFFER_SIZE
ここ戻して！

2023-11-02 08:42 UTC, MasaDevs commented
> 大丈夫そう！
> BufferSizeが１だとできないって認識であってます？

俺できたんだけどできなかったかい？

2023-11-02 08:46 UTC, MasaDevs commented on test/unit_test/request/srcs/main.cpp
> +#ifndef BUFFER_SIZE
3fa8c11

直しました。

2023-11-02 08:46 UTC, MasaDevs commented on srcs/server/request/parse_http_request.cpp
> +		http_line_stream_[socketfd] = "";
3fa8c11

直しました。

2023-11-04 05:18 UTC, soooku submitted a review, later dismissed

2023-11-11 12:36 UTC, libknt reviewed
okです！test書いてあってわかりやすいです！
testにいくつか抜けがあったのでよろしくです〜

2023-11-11 12:36 UTC, libknt commented on test/unit_test/request/srcs/main.cpp
>  			else
ここのtestにはexitが必要かな！
```
else {
std::cerr << "TEST" << argv[i] << ": NG" << request.getStatus() << std::endl;
exit(1);
}
```

2023-11-11 12:36 UTC, libknt commented on test/unit_test/request/Makefile
> +	@for number in `seq 1 1025`; do \
BUFFER_SIZEが2以上のときしかできない場合はseq 2 1025にしてほしい!
なんで1ができないか軽めにコメントも残してくれると嬉しい！!

2023-11-11 12:36 UTC, libknt commented on srcs/server/request/parse_http_request.hpp
> +	HttpRequest& getRequest(int sd);
const HttpRequest & getRequest(int sd) const ;
説ある？

2023-11-12 02:28 UTC, MasaDevs commented on srcs/server/request/parse_http_request.hpp
> +	HttpRequest& getRequest(int sd);
3972228dffe14d4684d0053dfa80271ae6a58c8f
直しました。

2023-11-12 02:32 UTC, MasaDevs commented on test/unit_test/request/Makefile
> +	@for number in `seq 1 1025`; do \
7eca53f432fa4b39978af3740542c824453484e0
サイズ1がダメな理由としては
char buffer[BUFFER_SIZE]にBUFFER_SIZE- 1で値を詰めないと最後がnull終端されないんだ。
BUFFER_SIZEが1だと、1−1で１文字も読めなくなってしまう。
これが理由ですな。

2023-11-12 02:33 UTC, MasaDevs commented on test/unit_test/request/srcs/main.cpp
>  			else
fd1b5df146c1413bb440149cdde24f1dc0415dbd
直しました。

2023-11-16 04:20 UTC, libknt approved these changes
lgtm

2023-11-16 05:19 UTC, soooku submitted a review, later dismissed
感謝！

2023-11-16 05:21 UTC, libknt commented on test/unit_test/request/Makefile
> +	@for number in `seq 1 1025`; do \
ついでにmainの最初にBUFFER_SIZEが1以下の場合ERRORにしてほしいかも！

2023-11-16 05:24 UTC, libknt approved these changes
ありがとう！
lgtm

2023-11-16 05:35 UTC, soooku approved these changes

2023-11-16 05:35 UTC, merged